ensime {
  imports {
    locals = false
    groups = ["java", "scala", "*", "scalaz", "org.ensime"]
    wildcards = ["scalaz", "scalaz.Scalaz"]
    collapseExclude = ["scala"]
  }
  index.batchSize = 100
}