# used when stack is invoked with --system-ghc
#
# stack install --system-ghc cabal-install xmobar pandoc xmonad xmonad-contrib
flags:
  xmonad-contrib:
    use_xft: true
  xmobar:
    with_xft: true
extra-package-dbs: []
packages: []
extra-deps:
  - xmonad-0.13
  - xmonad-contrib-0.13
  - xmobar-0.24
resolver: lts-10.0
