;;; smithy-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from smithy-mode.el

(autoload 'smithy-mode "smithy-mode" "\
Major mode for editing smithy IDL files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.smithy\\'" . smithy-mode))
(register-definition-prefixes "smithy-mode" '("smithy-"))

;;; End of scraped data

(provide 'smithy-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; smithy-mode-autoloads.el ends here
