[landscape]
name = Hometown
author = Sam Halliday
description = my backyard
type = spherical
maptex = astro_backyard.png
[location]
name = Auchterarder
planet = Earth
country = Scotland
# It's the 18th hole of my local golf course, you didn't think
# I'd be stupid enough to give away my home location, did you?
latitude = 56.291
longitude = -3.722
altitude = 75
